### PR TITLE
rename .env variable for zulip bot connection

### PR DESCRIPTION
**Pull request by atjbramley**
Related to Lecture 57 - clarifies that the `zulip_bot_name` env variable actually matches against the bot email stem.
Thank you for the course!

### CODE REVIEW

**Comment by predmijat** [comment]
Hey, I'm not sure I quite agree with this one though...when I see "email" I expect "something@domain.tld".
So while I do agree that the var matches the email prefix, I'm hesitant to call the variable "zulip_bot_email".

I hope that you've enjoyed the course :)

**Comment by atjbramley** [comment]
Yes - I agree, I was going to go with "zulip_bot_email_stem", but that starts sounding messy.
Do as you wish!  Just something that caught me out as I was making small changes from your examples.

The course has been excellent - I've recommended it to my colleagues!

**Comment by predmijat** [comment]
I'm thinking of editing the video and adding a notification there, but keeping the same var name...

**Comment by atjbramley** [comment]
As you wish!  It's a small thing, and there's now a comment in the Q&As that would help other people from running into this.

I guess, from a learner's perspective, there are parts of the course that I'm interested in, and there are parts of the course that I just want to work so that I can move to the next part that I'm especially interested in.  Zulip, great as it seems, is not a tool that I see myself learning deeper or using again, so I'm just trying to save someone else from having to hunt through the docs and be able to move on quickly.

**Comment by predmijat** [comment]
Completely understood. With this amount of apps/services, there's no way making everyone happy :)
But even if you don't like Zulip, I think it nicely showcases concepts/possibilities.

Uploading edited video in a few minutes - thanks for the input!

**Comment by atjbramley** [comment]
Yes - I agree - the apprise library is something I didn't know about, and I'll certainly be pushing notifications to some of the other endpoints that it can reach!

**Pull request closed without merging**
